### PR TITLE
Remove incrementals-publisher

### PR DESCRIPTION
**Pull request by jglick**
As of @halkeye’s https://github.com/jenkins-infra/pipeline-library/pull/163 this is now in https://github.com/jenkins-infra/incrementals-publisher.

### CODE REVIEW

**Comment by halkeye** [comment]
@timja @slide do we need to shut anything down on azure first? or because its serverless, as soon as we stop using it, its cleaned up and stuff?

**Comment by slide** [comment]
Azure is setup with integration with SCM, meaning that the functions are setup based on what is in this repo.  I believe this means that if it is removed from this repo, it will be removed from Azure.

**Comment by timja** [comment]
> Azure is setup with integration with SCM, meaning that the functions are setup based on what is in this repo. I believe this means that if it is removed from this repo, it will be removed from Azure.

Should be otherwise we can manually remove

**Review by timja — APPROVED** [review]

**Comment by slide** [comment]
Looks like it was removed on Azure.

**Pull request merged**
