### PR TITLE
chore: remove evergreen upload function

### PR DESCRIPTION
**Pull request by lemeurherve**
Removing it as it's not used anymore and as it's subject to almost 40 dependabot security alerts.

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by dduportal** [comment]
cc @timja @MarkEWaite @halkeye @daniel-beck are these "functions" still used anywhere? It looks to me that we shall archive the repository.

(Reason I'm asking is because the build on both the main branch and the PR here are both failing so this repository is not really taken care of)

**Comment by halkeye** [comment]
evergreen's been shut down for a while now. killl emmmmmmmm

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
FWIW nothing in this repo is used as far as I know. unless this does anything:
https://github.com/jenkins-infra/community-functions/tree/master/analytics-bouncer

**Comment by lemeurherve** [comment]
I'll archive this repo instead of merging this PR then.

We also need to check/clean/delete what's in the community function resource group on Azure.

**Pull request closed without merging**
