### PR TITLE
Refactor and add tests for INFRA-2183

### PR DESCRIPTION
**Pull request by halkeye**
* Switched index to a big class so its easier to override bits
* Split things up into smaller functions
* Fixed up all the await/async mess so its using promises everywhere,
  instead of random bits here and there
* Added happy path test and fixtures
* Added generic error handling to try to make things a bit less silent failure
* Made zip errors get surfaced (though not much is tested)

### CODE REVIEW

**Review by jglick — COMMENTED** [review]
I am not really qualified to review Node code. Maybe @rtyler, the main author, is.

Please bear in mind that it is crucial for security reasons that all existing input validations remain. (See JEP-305 for background.) I _think_ you preserved behavior here, though the diff is too long for me to really understand.

If you are working on this stuff you need to be able to check the behavior on the live “server” when it is deployed. Most of the functionality can be tested using either mocks or test accounts, but you never know what will happen in reality. I was never granted direct access (INFRA-2094) so I could only make changes when paired with someone from the infra team.

**Comment by rtyler** [comment]
Wow great work @halkeye, I'll try to wrap my brain around this sometime during this week as my schedule permits

**Comment by halkeye** [comment]
So I don't think there's actually a bug in the original code. So it's just a refactor now.

From Jesse and my manual tests earlier, Jenkins isn't showing the second line which contains the details 

So it's up to you if you want to risk this refactor

**Review by timja — APPROVED** [review]
This all looks sane to me, some good error handling improvements.

**Comment by halkeye** [comment]
I was so confused why i got a email about this. I totally forgot I wrote this PR

**Comment by timja** [comment]
> I was so confused why i got a email about this. I totally forgot I wrote this PR

just been poking around at how the function is setup and I saw this :D

**Pull request merged**
